name: Run container

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  container:
    runs-on: ${{ inputs.environment }}
    timeout-minutes: 10
    steps:
      - name: Deploy
        run: |
          project=${{ github.event.repository.name }}
          cd code-workspaces/sevria/deployments/local
          docker compose pull $project
          docker compose up -d $project
